name: build_and_publish_docs

on:
  push:
    branches:
    - dev
    - master
    - test/**
  pull_request:
    branches:
    - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/master' }}

jobs:
  publish:
    name: build and publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: fetch gh-pages branch
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          git checkout gh-pages
          git checkout ${{ env.BRANCH_NAME }}

      - name: set up python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.6'

      - name: setup poetry and install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          python -m poetry install --with tutorials,docs --all-extras --no-ansi --no-interaction

      - name: build documentation
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_BOT_USERNAME: ${{ secrets.TG_BOT_USERNAME }}
        run: |
          python -m poetry run poe docs

      - name: save branch name without slashes
        if: ${{ github.ref != 'refs/heads/master' }}
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          BRANCH_NAME=${{ env.BRANCH_NAME }}
          BRANCH_NAME=${BRANCH_NAME////_}
          echo BRANCH_NAME=${BRANCH_NAME} >> $GITHUB_ENV

      - name: save artifact
        uses: actions/upload-artifact@v4
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        with:
          name: ${{ format('github-pages-for-branch-{0}', env.BRANCH_NAME) }}
          path: docs/build/
          retention-days: 3

      - name: save branch, checkout to gh-pages and update switcher.json
        run: |
          git add -f .
          git stash
          cp docs/source/_static/switcher.json ./switcher.json
          ls
          git add .
          git stash
          ls
          git checkout gh-pages
          ls
          rm -f ./switcher.json
          ls
          git stash pop
          ls

      - name: delete previous docs build for this branch
        uses: EndBug/add-and-commit@v9.1.4
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        with:
          remove: '-r --ignore-unmatch ./${{ env.BRANCH_NAME }}'

      - name: checkout to original branch and reapply changes
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          git checkout ${{ env.BRANCH_NAME }}
          git stash pop

      - name: deploy website
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/build/
          clean: False
